config/routes.rb
BBS::Application.routes.draw do
  root 'topics#index'

  resources :users
  resources :topics, only: [:index, :create, :show, :new]
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :title, :presence => true, :length => {:maximum => 25}
  validates :body, :presence => true
end

app/models/user.rb
# coding: utf-8
class User < ActiveRecord::Base

  before_save {self.username = username.downcase}
  before_save {self.email = email.downcase}
  before_create :generate_remember_token


  validates :username,
            :presence => true,
            :length => {:maximum => 20},
            :uniqueness => {:case_sensitive => false}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email,
            :presence => true,
            :format => {:with => VALID_EMAIL_REGEX},
            :uniqueness => {:case_sensitive => false}

  validates :password,
            :presence => true,
            :length => {:minimum => 8,
                        :maximum => 20},
            :confirmation => {:message => '两次密码不一致'}

  validates :password_confirmation,
            :presence => true

  #validates_confirmation_of :password, :message => "两次密码不一致"


  def password
		@password
  end


  def password=(pass)
    return unless pass
    @password = pass
    generate_password(pass)
  end

  def password_confirmation
    @password_confirmation
  end

  def password_confirmation=(pass)
    return unless pass
    @password_confirmation = pass
  end


  # 密码认证
  def authenticate(pass)
    if Digest::SHA256.hexdigest(pass + self.salt) == self.hashed_password
      return self
    end
    false
  end


  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
    def generate_password(pass)
      salt = Array.new(10){rand(1024).to_s(36)}.join
      self.salt, self.hashed_password =
          salt, Digest::SHA256.hexdigest(pass + salt)
    end

    def generate_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      sign_in user
      sign_in_remember user if params[:session][:remember_me] == '1'

      redirect_to user
    else
      flash.now[:error] = "用户名或者密码错误"
      flash.keep
      redirect_to signin_path
    end

  end

  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      flash[:success] = "发帖成功"
      redirect_to topics_url
    else
      render 'new'
    end
  end

  private
    def topic_params
      params.require(:topic).permit(:title, :body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper

  def new
    @user= User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "注册成功,欢迎你 " + @user.username
      redirect_to @user
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:username,
                                   :email,
                                   :password,
                                   :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "BBS社区"
    if page_title.empty?
      base_title
    else
      page_title
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    session[:user_id] = user.id
    self.current_user = user
  end

  def sign_in_remember(user)
    #cookies[:remember_token] =user.remember_token
    cookies[:remember_token] = {
        value:   user.remember_token,
        expires: 2.weeks.from_now
    }
  end


  def sign_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) || User.find_by(remember_token: cookies[:remember_token])
  end


  def sign_out
    self.current_user = nil

    reset_session
    cookies.delete(:remember_token)
  end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end

end

app/views/layouts/_footer.slim
footer	class="footer"
	small
		a href="http://railstutorial.org/"
			| Rails Tutorial
		| by Michael Hartl
	nav
		ul
			li =link_to "About", '#'
			li =link_to "Contact", '#'
			li: a href="http://www.baidu.com" Rails

app/views/layouts/_header.slim
header class="navbar navbar-fixed-top navbar-inverse"
	div class="navbar-inner"
		div class="container"
			=link_to "sample app", "#", id: "logo"
			nav
				ul class="nav pull-right"
					li =link_to "Home", root_path
					li =link_to "Help", '#'
					- if sign_in?
						li id="fat-menu" class="dropdown"
							a href='#' class="dropdown-toggle" data-toggle="dropdown"
								|账户
								b class="caret"
							ul class="dropdown-menu"
								li =link_to '资料', current_user
								li =link_to '设置', '#'
								li class="divider"
								li =link_to "退出", signout_path, method: "delete"
					- else
						li =link_to '登陆', signin_path

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.slim
doctype html
html
	head
		title =full_title(yield(:title))
		= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
		= javascript_include_tag "application", "data-turbolinks-track" => true 
		= csrf_meta_tags
        = render 'layouts/shim'
    body
        = render 'layouts/header'
        div class="container"
            - flash.each do |key, value|
                div class="alert alert-#{key}"
                    = value
            = yield
            = render 'layouts/footer'
            = debug(params) if Rails.env.development?

app/views/shared/_error_messages.slim
- if @user.errors.any?
	div id="error_explanation"
		div class="alert alert-error"
			| 表单包含#{pluralize(@user.errors.count, "error")}个错误
		ul
			- @user.errors.full_messages.each do |msg|
				li 
					| * #{msg}

app/views/topics/index.html.slim
h1 最新主题

- @topics.each do |topic|
  h3 = link_to topic.title, topic
  p  = topic.body

p
	=link_to '新建主题', new_topic_path

app/views/topics/new.html.slim
= form_for @topic do |f|
  - if @topic.errors.any?
    #error_explanation
      h2 = "#{pluralize(@topic.errors.count, "error")} prohibited this topic from being saved:"
      ul
        - @topic.errors.full_messages.each do |message|
          li = message

  .field
    = f.label '标题'
    = f.text_field :title
  .field
    = f.label '正文'
    = f.text_area :body
  .actions = f.submit '发表'

app/views/topics/show.html.slim
p
  strong Title:
  = @topic.title
p
  strong Body:
  = @topic.body

app/views/users/new.slim
-provide(:title, '注册')
h1 注册
div class="row"
  div class="span6 offset3"
    = form_for(@user) do |f|
      = render 'shared/error_messages'

      = f.label :username
      = f.text_field :username

      = f.label :email
      = f.text_field :email

      = f.label :password
      = f.password_field :password

      = f.label :password_confirmation
      = f.password_field :password_confirmation

      = f.submit "注册", class: "btn btn-large btn-primary"

app/views/users/show.slim
- provide(:title, @user.username)


div class="row"
	aside class="span4"
		section
			h1
				= gravatar_for @user
				= @user.username